#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.3'
__CHEETAH_versionTuple__ = (2, 4, 3, 'development', 0)
__CHEETAH_genTime__ = 1289204075.119652
__CHEETAH_genTimestamp__ = 'Mon Nov  8 06:14:35 2010'
__CHEETAH_src__ = 'Base.tmpl'
__CHEETAH_srcLastModified__ = 'Mon Nov  8 06:01:54 2010'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class Base(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(Base, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r
<html xmlns="http://www.w3.org/1999/xhtml">\r
<head>\r
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />\r
<title>Albergue Amigo - ''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"title",True) # u'$title' on line 5, col 25
        if _v is not None: write(_filter(_v, rawExpr=u'$title')) # from line 5, col 25.
        write(u'''</title>\r
<link href="/style.css" rel="stylesheet" type="text/css" />\r
</head>\r
\r
<body>\r
<div id="main_header">\r
<div id="header">\r
  <ul>\r
    <li><a href="#" class="home" title="home">home</a></li>\r
    <li><a href="#" class="user" title="user">user</a></li>\r
    <li><a href="#" class="contact" title="contact">contact</a></li>\r
  </ul>\r
  <ul class="free">\r
    <li><a class="call">800-121-4545 759-121-5454</a></li>\r
  </ul>\r
  <img src="/images/logo.gif" alt="appleweb" width="205" height="65" title="appleweb" />\r
  <ul class="navi">\r
    <li><a href="#">Network</a></li>\r
    <li><a href="#">Submission</a></li>\r
    <li><a href="#">Archives</a></li>\r
    <li><a href="#">Finance</a></li>\r
    <li class="li1"><a href="#">Testimonials</a></li>\r
  </ul>\r
</div>\r
</div>\r
<div id="main_body">\r
<div id="body">\r
  <h2>''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"title",True) # u'$title' on line 32, col 7
        if _v is not None: write(_filter(_v, rawExpr=u'$title')) # from line 32, col 7.
        write(u'''</h2>\r
  ''')
        _v = VFSL([locals()]+SL+[globals(), builtin],"body",True) # u'$body' on line 33, col 3
        if _v is not None: write(_filter(_v, rawExpr=u'$body')) # from line 33, col 3.
        write(u'''\r
</div>\r
</div>\r
<div id="main_footer">\r
<div id="footer"><!--footer navigation start -->\r
<ul>\r
<li><a href="#" class="mg">Network</a>|</li>\r
<li><a href="#">Submission</a>|</li>\r
<li><a href="#"> Archives</a>|</li>\r
<li><a href="#">Finance</a>|</li>\r
<li><a href="#">Testimonials</a></li>\r
</ul>\r
<ul class="ad">\r
<li><a>Can Can Road 0128 Thonhill Canada</a></li>\r
<li class="nobor1"><a><span>ph:</span>\r
800-121-4545 759-121-5454</a></li>\r
<li class="nobor"><a><span>fax:</span>\r
759-121-5454 800-121-4545</a></li>\r
</ul>\r
<p>&copy; appleweb. All rights reserved.</p>\r
<p class="de">Designed by: <a href="http://www.templateworld.com/">Template World</a></p>\r
</div><!--footer navigation end -->\r
</div>\r
</body>\r
</html>\r
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_Base= 'respond'

## END CLASS DEFINITION

if not hasattr(Base, '_initCheetahAttributes'):
    templateAPIClass = getattr(Base, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(Base)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=Base()).run()


