#!/usr/bin/env python
# -*- coding: UTF-8 -*-




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Base import Base

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.3'
__CHEETAH_versionTuple__ = (2, 4, 3, 'development', 0)
__CHEETAH_genTime__ = 1291608400.5245681
__CHEETAH_genTimestamp__ = 'Mon Dec  6 02:06:40 2010'
__CHEETAH_src__ = 'Index.tmpl'
__CHEETAH_srcLastModified__ = 'Mon Dec  6 02:06:30 2010'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class Index(Base):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(Index, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def body(self, **KWS):



        ## CHEETAH: generated from #def body at line 5, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''<div id="welcome" class="boxed2">
\t\t\t<h1 class="title">Bem vindo Mendigo!</h1>
\t\t\t<div class="content">
\t\t\t\t<p><strong>Albergue Amigo</strong> \xc3\xa9 um sistema de busca de hoteis/albergues/caixa de f\xc3\xb3sforo e afins. Neste site voc\xc3\xaa vai encontrar o canto certo para cair b\xc3\xaabado! Al\xc3\xa9m disso, para cada pocilga mostraremos sua localiza\xc3\xa7\xc3\xa3o em mapa e as pocilgas ao redor. <em><strong>Aproveite! :)</strong></em></p>
\t\t\t</div>
\t\t</div>
\t\t<div id="sample1" class="boxed3">
\t\t\t<h2 class="title">Pocilgas ZL</h2>
\t\t\t<div class="content">
\t\t\t\t<ul>
\t\t\t\t\t<li><a href="#">Mauris vulputate dolor sit amet</a></li>
\t\t\t\t\t<li><a href="#">Nulla luctus eleifend purus</a></li>
\t\t\t\t\t<li><a href="#">Praesent scelerisque lorem</a></li>
\t\t\t\t\t<li><a href="#">Ut nonummy rutrum sem</a></li>
\t\t\t\t\t<li><a href="#">Pellentesque tempus quam</a></li>
\t\t\t\t\t<li><a href="#">Fusce ultrices fringilla metus</a></li>
\t\t\t\t\t<li><a href="#">Praesent mattis condimentuml</a></li>
\t\t\t\t</ul>
\t\t\t</div>
\t\t</div>
\t\t<div id="sample2" class="boxed3">
\t\t\t<h2 class="title">Pocilgas ZN</h2>
\t\t\t<div class="content">
\t\t\t\t<ol>
\t\t\t\t\t<li><a href="#">In posuere eleifend odio quisque semper augue mattis wisi maecenas ligula.</a></li>
\t\t\t\t\t<li><a href="#">Donec leo, vivamus fermentum nibh in augue praesent.</a></li>
\t\t\t\t\t<li><a href="#">Quisque dictum integer nisl risus sagittis convallis rutrum.</a></li>
\t\t\t\t</ol>
\t\t\t</div>
\t\t</div>
\t\t<div id="sample1" class="boxed3">
\t\t\t<h2 class="title">Pocilgas ZS</h2>
\t\t\t<div class="content">
\t\t\t\t<ul>
\t\t\t\t\t<li><a href="#">Mauris vulputate dolor sit amet</a></li>
\t\t\t\t\t<li><a href="#">Nulla luctus eleifend purus</a></li>
\t\t\t\t\t<li><a href="#">Praesent scelerisque lorem</a></li>
\t\t\t\t\t<li><a href="#">Ut nonummy rutrum sem</a></li>
\t\t\t\t\t<li><a href="#">Pellentesque tempus quam</a></li>
\t\t\t\t\t<li><a href="#">Fusce ultrices fringilla metus</a></li>
\t\t\t\t\t<li><a href="#">Praesent mattis condimentuml</a></li>
\t\t\t\t</ul>
\t\t\t</div>
\t\t</div>
\t\t<div id="sample2" class="boxed3">
\t\t\t<h2 class="title">Pocilgas ZO</h2>
\t\t\t<div class="content">
\t\t\t\t<ol>
\t\t\t\t\t<li><a href="#">In posuere eleifend odio quisque semper augue mattis wisi maecenas ligula.</a></li>
\t\t\t\t\t<li><a href="#">Donec leo, vivamus fermentum nibh in augue praesent.</a></li>
\t\t\t\t\t<li><a href="#">Quisque dictum integer nisl risus sagittis convallis rutrum.</a></li>
\t\t\t\t</ol>
\t\t\t</div>
\t\t</div>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def writeBody(self, **KWS):



        ## CHEETAH: main method generated for this template
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_Index= 'writeBody'

## END CLASS DEFINITION

if not hasattr(Index, '_initCheetahAttributes'):
    templateAPIClass = getattr(Index, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(Index)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=Index()).run()


