#!/usr/bin/env python
# -*- coding: UTF-8 -*-



##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Base import Base

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.0.1'
__CHEETAH_versionTuple__ = (2, 0, 1, 'final', 0)
__CHEETAH_genTime__ = 1292019176.3553951
__CHEETAH_genTimestamp__ = 'Fri Dec 10 20:12:56 2010'
__CHEETAH_src__ = 'ViewHotel.tmpl'
__CHEETAH_srcLastModified__ = 'Fri Dec 10 13:41:24 2010'
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class ViewHotel(Base):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        Base.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def head(self, **KWS):



        ## CHEETAH: generated from #def head at line 5, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&language=pt-br"></script>
<script type="text/javascript">
  function initialize() {
    var hotel = new google.maps.LatLng(''')
        _v = VFFSL(SL,"hotel.latitude",True) # '$hotel.latitude' on line 9, col 40
        if _v is not None: write(_filter(_v, rawExpr='$hotel.latitude')) # from line 9, col 40.
        write(''', ''')
        _v = VFFSL(SL,"hotel.longitude",True) # '$hotel.longitude' on line 9, col 57
        if _v is not None: write(_filter(_v, rawExpr='$hotel.longitude')) # from line 9, col 57.
        write(''');
    var myOptions = {
      zoom: 16,
      center: hotel,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    var hotelMarker = new google.maps.Marker({
      position: hotel, 
      map: map, 
      title:"''')
        _v = VFFSL(SL,"hotel.nome",True) # '$hotel.nome' on line 19, col 14
        if _v is not None: write(_filter(_v, rawExpr='$hotel.nome')) # from line 19, col 14.
        write('''"
\t});
\t
''')
        for i in range(len(VFN(VFFSL(SL,"nearby_sites",True),"keys",False)())): # generated from line 22, col 2
            s = VFN(VFFSL(SL,"nearby_sites",True),"keys",False)()[VFFSL(SL,"i",True)]
            write('''\tvar pos''')
            _v = VFFSL(SL,"i",True) # '$i' on line 24, col 9
            if _v is not None: write(_filter(_v, rawExpr='$i')) # from line 24, col 9.
            write(''' = new google.maps.LatLng(''')
            _v = VFFSL(SL,"s.latitude",True) # '$s.latitude' on line 24, col 37
            if _v is not None: write(_filter(_v, rawExpr='$s.latitude')) # from line 24, col 37.
            write(''', ''')
            _v = VFFSL(SL,"s.longitude",True) # '$s.longitude' on line 24, col 50
            if _v is not None: write(_filter(_v, rawExpr='$s.longitude')) # from line 24, col 50.
            write(''');
\tvar marker''')
            _v = VFFSL(SL,"i",True) # '$i' on line 25, col 12
            if _v is not None: write(_filter(_v, rawExpr='$i')) # from line 25, col 12.
            write(''' = new google.maps.Marker({
\t  icon: "/images/beerMarker.png",
      position: pos''')
            _v = VFFSL(SL,"i",True) # '$i' on line 27, col 20
            if _v is not None: write(_filter(_v, rawExpr='$i')) # from line 27, col 20.
            write(''', 
      map: map, 
      title:"''')
            _v = VFFSL(SL,"s.name",True) # '$s.name' on line 29, col 14
            if _v is not None: write(_filter(_v, rawExpr='$s.name')) # from line 29, col 14.
            write('''"
\t});
\t
\tvar content''')
            _v = VFFSL(SL,"i",True) # '$i' on line 32, col 13
            if _v is not None: write(_filter(_v, rawExpr='$i')) # from line 32, col 13.
            write(''' = "Hotel: ''')
            _v = VFFSL(SL,"s.name",True) # '$s.name' on line 32, col 26
            if _v is not None: write(_filter(_v, rawExpr='$s.name')) # from line 32, col 26.
            write('''<br>";
\tvar infoWindow''')
            _v = VFFSL(SL,"i",True) # '$i' on line 33, col 16
            if _v is not None: write(_filter(_v, rawExpr='$i')) # from line 33, col 16.
            write(''' = new google.maps.InfoWindow({content: content''')
            _v = VFFSL(SL,"i",True) # '$i' on line 33, col 65
            if _v is not None: write(_filter(_v, rawExpr='$i')) # from line 33, col 65.
            write('''});
\t(infoWindow''')
            _v = VFFSL(SL,"i",True) # '$i' on line 34, col 13
            if _v is not None: write(_filter(_v, rawExpr='$i')) # from line 34, col 13.
            write(''').setPosition(pos''')
            _v = VFFSL(SL,"i",True) # '$i' on line 34, col 32
            if _v is not None: write(_filter(_v, rawExpr='$i')) # from line 34, col 32.
            write(''');
    (infoWindow''')
            _v = VFFSL(SL,"i",True) # '$i' on line 35, col 16
            if _v is not None: write(_filter(_v, rawExpr='$i')) # from line 35, col 16.
            write(''').open(map);
\t
''')
        write('''\t
\tvar content = "Hotel: ''')
        _v = VFFSL(SL,"hotel.nome",True) # '$hotel.nome' on line 39, col 24
        if _v is not None: write(_filter(_v, rawExpr='$hotel.nome')) # from line 39, col 24.
        write('''<br> Classifica\xc3\xa7ao: ''')
        _v = VFFSL(SL,"hotel.classificacao",True) # '$hotel.classificacao' on line 39, col 56
        if _v is not None: write(_filter(_v, rawExpr='$hotel.classificacao')) # from line 39, col 56.
        write(''' estrelas<br>"
\tvar infoWindow = new google.maps.InfoWindow({content: content});
\tinfoWindow.setPosition(hotel);
    infoWindow.open(map);
  }

</script>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def body(self, **KWS):



        ## CHEETAH: generated from #def body at line 48, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''<h2>''')
        _v = VFFSL(SL,"hotel.nome",True) # '$hotel.nome' on line 49, col 5
        if _v is not None: write(_filter(_v, rawExpr='$hotel.nome')) # from line 49, col 5.
        write('''</h2>
<p>Endereco: ''')
        _v = VFFSL(SL,"hotel.endereco",True) # '$hotel.endereco' on line 50, col 14
        if _v is not None: write(_filter(_v, rawExpr='$hotel.endereco')) # from line 50, col 14.
        write('''</p>
<p>Classificacao: ''')
        _v = VFFSL(SL,"hotel.classificacao",True) # '$hotel.classificacao' on line 51, col 19
        if _v is not None: write(_filter(_v, rawExpr='$hotel.classificacao')) # from line 51, col 19.
        write('''</p>
<div id="map_canvas" style="width: 500px; height: 480px;"></div>
<br/>
<h2>S\xc3\xadtios Tur\xc3\xadsticos Pr\xc3\xb3ximos</h2>
<ul>
''')
        for site,dist in VFN(VFFSL(SL,"nearby_sites",True),"items",False)(): # generated from line 56, col 1
            write('''<li><b>''')
            _v = VFFSL(SL,"site.name",True) # '$site.name' on line 57, col 8
            if _v is not None: write(_filter(_v, rawExpr='$site.name')) # from line 57, col 8.
            write('''</b> - ''')
            _v = VFFSL(SL,"dist",True) # '$dist' on line 57, col 25
            if _v is not None: write(_filter(_v, rawExpr='$dist')) # from line 57, col 25.
            write(''' m</li>
''')
        write('''</ul>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def writeBody(self, **KWS):



        ## CHEETAH: main method generated for this template
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''

''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_ViewHotel= 'writeBody'

## END CLASS DEFINITION

if not hasattr(ViewHotel, '_initCheetahAttributes'):
    templateAPIClass = getattr(ViewHotel, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(ViewHotel)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=ViewHotel()).run()


